[build]

  # This command builds the site
  command = "npm install && npm run build"

  # This is the directory that will be deployed
  publish = "build"

  # This is where our functions are located
  functions = "functions"
